title: "Ideas"
body:
  - type: markdown
    attributes:
      value: |
        Share ideas for new features
  - type: markdown
    id: showcase
    attributes:
      label: Showcase
      description: "Practical example or scenario demonstrating the impact of the idea"
      render: auto
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking changes
      description: Indicate if your idea introduces changes that require altering any current behavior
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
