blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/:vendor/:library-name/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Ask a Question
    url: https://github.com/:vendor/:library-name/discussions/new?category=q-a
    about: Ask the community for help
  - name: Questions & Discussions
    url: https://github.com/:vendor/:library-name/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
