name: validate

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/dependencies
      - name: checking library types
        run: npm run vue type-check

  build:
    runs-on: ubuntu-latest
    needs: type-check

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/dependencies
      - name: build library
        run: npm run vue build-only
      - name: build cli
        run: npm run vue build:cli

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/dependencies
      - name: lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/dependencies
      - name: code formatting
        run: npm run format
